version: '3.8'

services:
  db:
    image: mysql:8.0 # https://hub.docker.com/_/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=frozenit
    ports:
      - 3307:3306
    volumes: # https://docs.docker.com/storage/volumes/
      - "./db/DDL.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/DML.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./db/AUTH.sql:/docker-entrypoint-initdb.d/3.sql"

